/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mike' at '30/12/15 14:10' with Gradle 2.9
 *
 * @author mike, @date 30/12/15 14:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
